services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app               # 🔥 LIVE CODE
      - ./data:/mnt/data     # DB persistence
      - /app/node_modules    # prevent overwrite
    environment:
      NODE_ENV: development
      SHOPIFY_API_KEY: da279a758c5dc828269a5d77b585be37
      SHOPIFY_API_SECRET: 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
      SHOPIFY_APP_URL: https://xxxx.ngrok-free.dev
      SCOPES: read_products,write_products,read_content,write_content
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"