# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "da279a758c5dc828269a5d77b585be37"
name = "testral-2"
application_url = "https://unrequited-tierra-nondiverging.ngrok-free.dev"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_content,read_products,write_content,write_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://unrequited-tierra-nondiverging.ngrok-free.dev" ]
