name: Deploy

on:
  workflow_run:
    workflows: ["Build & Push"]   # must match CI name exactly
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: SSH Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          passphrase: ${{ secrets.SERVER_PASSPHRASE }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/shopify-app:latest

            docker stop shopify-app || true
            docker rm shopify-app || true

            docker run -d \
              --name shopify-app \
              -p 3000:3000 \
              --env-file /opt/shopify-testral/.env \
              ${{ secrets.DOCKER_USERNAME }}/shopify-app:latest
